# Generated by Django 6.0.5 on 2026-05-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('recovery_agent_name', models.CharField(max_length=100)),
                ('recovery_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recovery_status', models.CharField(choices=[('Customer Payment', 'Customer Payment'), ('Godowned', 'Godowned'), ('Released', 'Released')], max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
