# Generated by Django 6.0.5 on 2026-05-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoverycase',
            old_name='recovery_agent_name',
            new_name='agent_name',
        ),
        migrations.RenameField(
            model_name='recoverycase',
            old_name='payment_amount',
            new_name='agent_pay',
        ),
        migrations.RenameField(
            model_name='recoverycase',
            old_name='recovery_commission',
            new_name='customer_amount',
        ),
    ]
